BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    XXXX XXXXXXXX XXXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    BBBB BBBBBB
  
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
	
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
  XXXXXX
    XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
					XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
					
					
				XXXXXX
				XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX
				XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
					XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
					
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
					XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
					
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
				XXXXXX
				XXXXXX
				
			XXXXXX
		XXXXXX
	XXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XX
		
		XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
			
		XXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
			XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXX XX
					XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
				XXX XXXXXXXXXXXXXXX XXXXXXXX
					XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
				XXXXX
				XXX XXXXXXXXXXXXXXXXX
					XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
				XXX XXXXXXXXXXXXXXXXX
					XX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
				XXX XXXXXXXXXXXXXXX XX
					XX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
				XXX XXXXXXXXXXXXXXXXX
					XX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
				
				XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX
					XX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
				XXXXX
			XXXXX
		XXXXXX
	XXXXXX
	
	XXXXXXXX XXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XX
		
			XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			
		
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXX
		XXXXXX
	XXXXXXXXXX

	XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
			XXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XX
					XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX
						XXXX XXXXXXXXXXXXXXXXXXXX
							XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXXXXXX XX
						XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
						XXX XXXXXXXX X XXXXXXX X XXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXX X XXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXX XXX
 XXXXX X XXXXX  XX XXXXXXXXXXXX XXXXXXXX XXXXXXXXX XX XXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXX XX XXXX XXXXX XXXXXX XX XXXXXXXX
XXXXX XXX XX XXXXXXXXX  
X XXX XX XXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX X XXXXX XXXXXXXXXXXXX 
XXXXX XXXXX X XXXXXX X XXX XXX XXXXXX XXXXX XX
 XXXXX XXXXXX XXXXXXXX X XXXXXXXX
XXXXXX XXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXX XXX XXXXXXXXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXX XXXX XXXXX 
XXXXXXXXXX XX XXXXXX XXXXXXX XXX XXXXXXXXXXX X XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX X XXXXXXXXX X XXXXXXX XXXXXXX
XXX XXXXXXXXXX 
XX XXXXXX XXXXXXXX XXXX XX XXXXX XXXXXXXXXXXXXX
XXXXXXXXXXXXX XX XXXXX X XXXXXXX XXXX XXXXXXXX X XXXXXX XXXXX XX XXXXX XXXXX XXXXXX XXXXXX XXXX XXXXXXXX XXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX
X XXXXXXXX X XXXXX XXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXX X XXXXXXXXXXXX XXXXXXXX XXXXX
						XXXXXXX
						XXXXXX
						
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXX XXX
  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
XXXXXX
BBBBBBBB