BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    XXXX XXXXXXXX XXXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    BBBB BBBBBB
  
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
	
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
  XXXXXX
    XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
					XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
					
					
				XXXXXX
				XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX
				XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
					XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
					
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
					XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
					
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
				XXXXXX
				XXXXXX
				
			XXXXXX
		XXXXXX
	XXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XX
		
		XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
			
		XXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
			XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXX XX
					XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
				XXX XXXXXXXXXXXXXXXXX
					XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
				XXXXX
				XXX XXXXXXXXXXXXXXX XX
					XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
				XXX XXXXXXXXXXXXXXX XXXXXXXX
					XX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
				XXX XXXXXXXXXXXXXXX XX
					XX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
				XXX XXXXXXXXXXXXXXXXX
					XX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
				
				XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX
					XX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
				XXXXX
			XXXXX
		XXXXXX
	XXXXXX
	XXXXXXXX XXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XX
		
			XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			
		
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX
		XXXXXX
	XXXXXXXXXX
	
	XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
		XXXXX XXXXXX XXXXXXXXXX
	XXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXX XXX
  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
XXXXXX
BBBBBBBB